export const FETCH_CITIES = 'FETCH_CITIES';
export const SELECT_CHECKIN_CHECKOUT_DATE = 'SELECT_CHECKIN_CHECKOUT_DATE';
export const SELECT_CITY = 'SELECT_CITY';
export const SEARCH_HOTELS = 'SEARCH_HOTELS';
export const BOOK_HOTELS ='BOOK_HOTELS';
export const BOOKING_CONFIRMED = 'BOOKING_CONFIRMED';
export const BOOKING_FAILED = 'BOOKING_FAILED';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const HOTEL_FACILITES = 'HOTEL_FACILITIES';
export const ROOM_FACILITIES = 'ROOM_FACILITIES';




