export const FETCH_CITIES = 'FETCH_CITIES';
export const SELECT_CHECKIN_CHECKOUT_DATE = 'SELECT_CHECKIN_CHECKOUT_DATE';
export const SELECT_CITY = 'SELECT_CITY';
export const SEARCH_HOTELS = 'SEARCH_HOTELS';
export const BOOK_HOTELS ='BOOK_HOTELS';
export const BOOKING_CONFIRMED = 'BOOKING_CONFIRMED';
export const BOOKING_FAILED = 'BOOKING_FAILED';



